# Generated by Django 4.2.7 on 2023-11-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='duree_preparation',
            field=models.TimeField(verbose_name='Temps de preparation'),
        ),
    ]
