# Generated by Django 4.2.7 on 2023-11-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_alter_recette_duree_preparation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recette',
            name='duree_preparation',
            field=models.DurationField(verbose_name='Temps de preparation'),
        ),
    ]
